name: Update Swagger Docs

on:
  push:
    branches:
      - main
    paths:
      - "purism-ev_api-current-resolved.yaml"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  update-docs:
    permissions:
      contents: "write"
      pull-requests: write
      id-token: "write"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install -g @redocly/cli

      - name: Generate API docs
        run: |
          npx @redocly/cli build-docs ./purism-ev_api-current-resolved.yaml --output=index.html
          mv index.html docs/index.html

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update API docs"
          git push origin main
